### ISSUE TITLE
NEEの光源寄与の処理、light_dist2の判定の処理について

### ISSUE THREAD

**Issue by Ushio** [ProjectAsura/sample_pt2#1]
こんにちは
遅らせながら、ブログ拝見いたしました。シンプルなところからとても整理されており、G項扱いの例も大変参考になりました！

本題なのですが、
ブログの中の画像で、基本のPTと、NEEの処理のレンダリング画像に明るさの違いが気になり、ちょっとソースを追いかけてみました。２点ほど気になる点があります。

１点目ですが、MISを行わないシンプルなNEEの場合、光源に直接当たった場合の寄与が初回以外については直接サンプリングですべて賄われるため、寄与に判定が必要のように思いました。
LTEの級数展開でいうところの、
       
L = Le + TLe + T^2 Le .....

最初のLeについては寄与を含める必要がありますが、残りはすべて直接サンプリングでの寄与で賄われる点です。（デルタ関数になってしまうマテリアルについては、延期されます）

２点目として、寄与が取れる場合 の判定ですが、

` if (dot0 >= 0 && dot1 >= 0 && light_dist2 >= rad2) `

の部分が、

` if (dot0 >= 0 && dot1 >= 0 && light_dist2 >= 0.00001) `

のようなゼロ除算回避のものを意図していたのではないかという点です。

以上を修正してみました。
https://github.com/Ushio/sample_pt2/commit/a8863006b599ee65cb5fb492e3ef45452b23b74e

こちらフォーク致しましたリポジトリです。
https://github.com/Ushio/sample_pt2

するとPTの場合と明るさがほぼ一致し、収束はとても早く、なおかつNEEの弱点でもある、

・パス長が短いケースにおけるファイアフライノイズ
・コースティクスパス（LS+DE）をうまく扱えない。※そもそも寄与が取れない？（ちょっと自信がありません）

というのが露呈しているのを確認することができました。

PT
![sample_pt](https://user-images.githubusercontent.com/1667893/28126828-9e74456a-6765-11e7-8453-18e433355b81.png)

PT, NEE
![sample_nee](https://user-images.githubusercontent.com/1667893/28126865-baa983ee-6765-11e7-8e5a-7f1896678c8b.png)

いかがでしょうか？

**Comment by Ushio** [comment]
先の実装でそもそも寄与が取れない件については、
代わりに同じ経路である、直接ぶつかった時の寄与（暗黙の、というのでしょうか）を一時的に差し込むことで、すべての経路をカバーできたように思います。
https://github.com/Ushio/sample_pt2/commit/3a6f60f0f7d906bebec96bc35185e16d4244c2ae

例えばRefractionの場合の
![refract](https://user-images.githubusercontent.com/1667893/28147225-083c1e92-67ba-11e7-884c-a000ec93a934.png)

という経路です。

これなら以下のように非常にPTと同じ見た目になりました。
ただ分岐が多く、ちょっと泥臭くはある気はします。。
![sample_sample_nee_ls de](https://user-images.githubusercontent.com/1667893/28147122-572e9be8-67b9-11e7-9be7-193213582ea8.png)

**Comment by ProjectAsura** [comment]
ご指摘ありがとうございます。
list_dist2の判定ですが，ファイアフライノイズが発生するため，適当な値で条件を絞ろうとして追加していたものです。この処理には何の理論的根拠なく，指摘のように正しい色でなくなるという問題があります。
うしおさんの指摘は，ごもっともな意見ですので，こちらのmasterブランチにも
Ushio/sample_pt2@3a6f60f
までの修正と同じ内容を入れました。
ProjectAsura/sample_pt2@4836d2b 

ファイアフライノイズについては，除去することが出来ないため，中央値フィルタを導入して対策を行いました。
ProjectAsura/sample_pt2@b9d1162
ディテールが結構失われますが，ノイズが入っているよりかはマシかなと思っています。
確認して頂き，問題ないようであればCloseしようと思います。

**Comment by ProjectAsura** [comment]
ご指摘部分，修正をmasterブランチに取り込み済みです。
…が，こちらの実装がそもそもあっていない箇所がありそうで，
すべてをdiffuseにしてもfireflyノイズが出ているような状況です。
こちらの問題が解決次第closeとしたいと思います。

**Comment by ProjectAsura** [comment]
いろいろと調べてみましたが，光源近くに衝突点がありサンプルされるものがあるとfireflyノイズが発生してしまうようです。現状回避策が無いので，一旦クローズとします。
